/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdminWorkArea;

import business.EcoSystems;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;


/**
 *
 * @author ayush
 */
public class BusinessAnalysisJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BusinessAnalysisJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystems system;

    public BusinessAnalysisJPanel(JPanel userProcessContainer, EcoSystems system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curretnCustomerAnalysisBtn = new javax.swing.JButton();
        predictiveAnalysisBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        backBtn = new javax.swing.JButton();

        curretnCustomerAnalysisBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        curretnCustomerAnalysisBtn.setText("Current Customers Water Usage Analysis");
        curretnCustomerAnalysisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curretnCustomerAnalysisBtnActionPerformed(evt);
            }
        });

        predictiveAnalysisBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        predictiveAnalysisBtn.setText("Predictive Analysis");
        predictiveAnalysisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predictiveAnalysisBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 20)); // NOI18N
        jLabel1.setText("Predictive Analysis");

        backBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 16)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(curretnCustomerAnalysisBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backBtn)
                                .addComponent(predictiveAnalysisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(curretnCustomerAnalysisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(predictiveAnalysisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void curretnCustomerAnalysisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curretnCustomerAnalysisBtnActionPerformed
        // TODO add your handling code here:
        CustomerWaterUsageAnalysisJPanel customerWaterUsageAnalysisJPanel=new CustomerWaterUsageAnalysisJPanel(userProcessContainer, system);
        userProcessContainer.add("customerWaterUsageAnalysisJPanel", customerWaterUsageAnalysisJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_curretnCustomerAnalysisBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void predictiveAnalysisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predictiveAnalysisBtnActionPerformed
        // TODO add your handling code here:
        PredictiveAnalysisJPanel predictiveAnalysisJPanel = null;
        try {
            predictiveAnalysisJPanel = new PredictiveAnalysisJPanel(userProcessContainer, system);
        } catch (ParseException ex) {
            Logger.getLogger(BusinessAnalysisJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        userProcessContainer.add("predictiveAnalysisJPanel", predictiveAnalysisJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_predictiveAnalysisBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton curretnCustomerAnalysisBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton predictiveAnalysisBtn;
    // End of variables declaration//GEN-END:variables
}
